### ISSUE TITLE
响影到聊天框功能

### ISSUE THREAD

**Issue by aixiu** [starpt/BiechuUnitFrames#1]
启用BiechuUnitFrames时，聊天框
![image](https://github.com/user-attachments/assets/55c55477-2f9a-4c7c-8009-21a078b4fa2a)
这三个按钮功能失效，并且右键这三个按钮会弹出一个
![image](https://github.com/user-attachments/assets/58e0e9c3-3abc-4974-820f-5156febc877e)
不知道这是调整哪里的，禁用BiechuUnitFrames时，上述两种情况消失！！
另发现报错：
1x [ADDON_ACTION_BLOCKED] 插件 'BiechuUnitFrames' 尝试调用保护功能 'PetFrameToT:Hide()'。
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@BiechuUnitFrames/Player.lua"]:487: in function <BiechuUnitFrames/Player.lua:434>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
本人挺喜欢这个框架的，希望大佬能修复下，谢谢啦！~！

**Comment by starpt** [comment]
看你报错信息是因为 PetFrameToT:Hide() 问题,
最新版本已经取消此方法了. 你可以下载最新的试试.
如有问题,可以加群,直接沟通.
